version: '3.9'

services:

  frontend:
    container_name: cdv-frontend
    build: ./front-end/
    depends_on:
      - "backend"
    ports:
      - "8081:80"

  backend:
    container_name: cdv-backend
    build: ./back-end/
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    #restart: always
  
  db:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=cBShnWkAh5i7t4Je
      - MSSQL_PID=Express
    restart: always